services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1010:1010"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chatapp
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - server

  db:
    image: postgres:14
    container_name: chat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
